### PR TITLE
Updated to OpenAI API v1 and replaced "function call" to "tool call"

### PR DESCRIPTION
**Pull request by yukoba**
Hello. The Local-Code-Interpreter is great and convenient! When I used it with gpt-4o-2024-08-06, it was unstable, so I upgraded the OpenAI API to version 1.40.3 and changed "function call" to "tool call." I also changed the default from GPT-3.5 to GPT-4. I confirmed that it works with Python 3.12.

I have implemented AzureOpenAI, and it probably works correctly, but I have not verified its operation.

Please note that this pull request does not include it, but in the case of gpt-4o-2024-08-06, "5. Response in the same language as the user." might be changed to "5. Response in English." Otherwise, there is a high probability of returning a response in the wrong language.

### CODE REVIEW

**Comment by MrGreyfun** [comment]
Hi, Thank you for this PR. I'm glad to see your implementation of items from the TODO list. Before merging, I think the model names `gpt-4-turbo`, `gpt-4o`, and `gpt-4o-mini` should be added to the config.json and README.

**Comment by MrGreyfun** [comment]
Yes, these model names are pointed to the newest version of the corresponding models, and should be added to the config.json and README.

**Comment by yukoba** [comment]
I added gpt-4-turbo, gpt-4o, and gpt-4o-mini to config.json and README.

**Comment by MrGreyfun** [comment]
I have merged this PR. Thank you once again for your contributions to the project.

**Pull request merged**
